# Generated by Django 3.0.1 on 2019-12-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumCovered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumName', models.CharField(blank=True, max_length=256, verbose_name='앨범이름')),
                ('img_path', models.CharField(max_length=512, null=True, verbose_name='커버사진경로')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='발매일')),
            ],
            options={
                'verbose_name': '커버곡 앨범',
                'verbose_name_plural': '커버곡 앨범',
                'db_table': 'albom_covered',
            },
        ),
        migrations.CreateModel(
            name='AlbumOwn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumName', models.CharField(max_length=256, null=True, verbose_name='앨범이름')),
                ('img_path', models.CharField(max_length=512, null=True, verbose_name='커버사진경로')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='발매일')),
            ],
            options={
                'verbose_name': '자작곡 앨범',
                'verbose_name_plural': '자작곡 앨범',
                'db_table': 'albom_own',
            },
        ),
    ]
