# Generated by Django 3.0.1 on 2019-12-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songcovered',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='songown',
            name='file_path',
        ),
        migrations.AddField(
            model_name='songcovered',
            name='bucketName',
            field=models.CharField(default='', max_length=128, verbose_name='버킷이름'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songcovered',
            name='key',
            field=models.CharField(default='', max_length=128, verbose_name='파일 이름'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songown',
            name='bucketName',
            field=models.CharField(default='', max_length=128, verbose_name='버킷이름'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songown',
            name='key',
            field=models.CharField(default='', max_length=128, verbose_name='파일 이름'),
            preserve_default=False,
        ),
    ]
