# Generated by Django 3.0.1 on 2020-01-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20191231_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songcovered',
            name='comment',
            field=models.TextField(null=True, verbose_name='평가'),
        ),
        migrations.AlterField(
            model_name='songown',
            name='comment',
            field=models.TextField(null=True, verbose_name='평가'),
        ),
    ]
