# Generated by Django 3.0.1 on 2020-01-14 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20200114_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongRecommended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='추천 날짜')),
                ('songCovered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='song.SongCovered', verbose_name='추천 할 커버곡')),
                ('songOwn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='song.SongOwn', verbose_name='추천 할 자작곡')),
            ],
            options={
                'verbose_name': '추천곡',
                'verbose_name_plural': '추천곡',
                'db_table': 'song_recommended',
            },
        ),
    ]
