# Generated by Django 3.0.1 on 2020-01-16 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_songrecommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrecommended',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='추천 날짜'),
        ),
    ]
