# Generated by Django 3.0.1 on 2020-01-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_auto_20200116_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='songcovered',
            name='check',
            field=models.BooleanField(default=False, verbose_name='검사 여부'),
        ),
        migrations.AddField(
            model_name='songown',
            name='check',
            field=models.BooleanField(default=False, verbose_name='검사 여부'),
        ),
    ]
