# Generated by Django 3.0.1 on 2020-01-17 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_auto_20200116_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrecommended',
            name='recommended_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='추천 날짜'),
        ),
        migrations.AlterField(
            model_name='songrecommended',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록 날짜'),
        ),
    ]
